name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.17"
        
      # make the binary
      - run: make GOOS=${{matrix.os}} GOARCH=${{matrix.arch}}

      - name: Build Docker images
        uses: docker/build-push-action@v2
